Repository runestone2023/Group-C, pull requests merged in 2023-04, with the labels that each got.

#12 Feature/initial project structure
  .gitattributes
  .gitignore
  README.md
  frontend/.gitignore
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  robosistance/.gitignore
  robosistance/Cargo.lock
  robosistance/Cargo.toml
  robosistance/src/main.rs
  robot/main.py
Labels: Backend, Frontend

#30 Feature/mock frontend endpoints
  robosistance/Cargo.lock
  robosistance/Cargo.toml
  robosistance/src/endpoints/mod.rs
  robosistance/src/endpoints/robot.rs
  robosistance/src/endpoints/ui.rs
  robosistance/src/main.rs
Labels: Backend

#33 Added information about the review process
  README.md
Labels: documentation
